  $ ./run.exe
  [O | _.14]
  [S (O); O | _.18]
  [S (O); S (O); O | _.22]
  [S (O); S (O); S (O); O | _.26]
  [S (O); S (O); S (O); S (O); O | _.30]
  [S (O); S (O); S (O); S (O); S (O); O | _.34]
  [S (O); S (O); S (O); S (O); S (O); S (O); O | _.38]
  [S (O); S (O); S (O); S (O); S (O); S (O); S (O); O | _.42]
  [S (O); S (O); S (O); S (O); S (O); S (O); S (O); S (O); O | _.46]
  [S (O); S (O); S (O); S (O); S (O); S (O); S (O); S (O); S (O); O | _.50]
  []
  [S (O)]
  [S (O); S (O)]
  [S (O); S (O); S (O)]
  [S (O); S (O); S (O); S (O)]
  [S (O); S (O); S (O); S (O); S (O)]
  [S (O); S (O); S (O); S (O); S (O); S (O)]
  [S (O); S (O); S (O); S (O); S (O); S (O); S (O)]
  [S (O); S (O); S (O); S (O); S (O); S (O); S (O); S (O)]
  [S (O); S (O); S (O); S (O); S (O); S (O); S (O); S (O); S (O)]
